version: '2'
services:
  homebridge:
    build: ./homebridge
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=America/Winnipeg
      - PGID=1000
      - PUID=27
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Winnipeg
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: host
    volumes:
      - /mnt/md0/plex/cfg:/config
      - /mnt/md0/plex/tv:/data/tv
      - /mnt/md0/plex/movies:/data/movies
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Winnipeg
    volumes:
      - ./transmission:/config
      - /mnt/md0/plex/tv:/mnt/media/torrents
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./jackett/config:/config
      - /mnt/md0/media/torrents/completed:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - ./sonarr/config:/config
      - /mnt/md0/plex/tv:/mnt/media
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - ~/docker-services/radarr/config:/config
      - /mnt/md0/plex/movies:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped
