version: '2'
services:
  homebridge:
    build: ./homebridge
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=America/Winnipeg
      - PGID=1000
      - PUID=27
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Winnipeg
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: host
    volumes:
      - /mnt/md0/plex/cfg:/config
      - /mnt/md0/plex:/data
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Winnipeg
    volumes:
      - ./transmission:/config
      - /mnt/md0/media/torrents:/mnt/media/torrents
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./jackett/config:/config
      - /mnt/md0/media/torrents/completed:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:3.0.9
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - ./sonarr/config:/config
      - /mnt/md0/plex/tv:/mnt/media
      - /mnt/md0/media/torrents:/mnt/media/torrents
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:4.3.2
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - ./radarr/config:/config
      - /mnt/md0/plex/movies:/mnt/media
      - /mnt/md0/media/torrents:/mnt/media/torrents
    ports:
      - 7878:7878
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
